package ingredients;

public enum DryIngredient {
	CORN_STARCH, POTATO_STARCH, TAPIOCA_STARCH, RICE_FLOUR_WHITE, RICE_FLOUR_WHOLEGRAIN, 
	SUGAR, SALT, E471, PSYLLIUM_HUSK, BUCKWHEAT, XANTHAM_GUM,XANTHAM_GUM_CARGIL, SUNFLOWER_SEEDS, MILLET_SEEDS, LINSEED_GOLDEN, LINSEED_DARK
}
